### ISSUE TITLE
Jackson error parsing mochawesome results

### ISSUE THREAD

**Issue by kevinstembridge** [wimdeblauwe/testcontainers-cypress#42]
I sometimes get this error when running my tests. It's trying to parse the attached file. 

com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `io.github.wimdeblauwe.testcontainers.cypress.MochawesomeGatherTestResultsStrategy$MochawesomeSpecRunReport$Result` (although at least one Creator exists): no boolean/Boolean-argument constructor/factory method to deserialize from boolean value (false)
 at [Source: (File); line: 20, column: 5] (through reference chain: io.github.wimdeblauwe.testcontainers.cypress.MochawesomeGatherTestResultsStrategy$MochawesomeSpecRunReport["results"]->java.util.ArrayList[0])
	at app//com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at app//com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1728)
	at app//com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1353)
	at app//com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromBoolean(ValueInstantiator.java:358)
	at app//com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromBoolean(StdValueInstantiator.java:494)
	at app//com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromBoolean(BeanDeserializerBase.java:1558)
	at app//com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:205)
	at app//com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:186)
	at app//com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
	at app//com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at app//com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at app//com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at app//com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
	at app//com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at app//com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at app//com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4675)
	at app//com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3495)
	at app//io.github.wimdeblauwe.testcontainers.cypress.MochawesomeGatherTestResultsStrategy.gatherTestResults(MochawesomeGatherTestResultsStrategy.java:40)
	at app//io.github.wimdeblauwe.testcontainers.cypress.CypressContainer.getTestResults(CypressContainer.java:258)

[mochawesome.txt](https://github.com/wimdeblauwe/testcontainers-cypress/files/8056911/mochawesome.txt)

**Comment by wimdeblauwe** [comment]
What version are you using? Are you using the Cypress version that is default for that version or a different one?

**Comment by kevinstembridge** [comment]
Hi Wim,

It looks as though this was caused by having a new spec file that didn't have any tests in it yet. (i.e. only the 'describe' but without any 'it's). So it wouldn't  be a problem under normal circumstances. 

You might choose not to cater for this scenario, which is fine by me if you want to close this issue.

FWIW, I'm using cypress 9.3.1.

**Comment by wimdeblauwe** [comment]
Thanks for letting me know. I'll leave the issue open and have a look if I do a new release in the future, but I won't to a special release now for it.

**Comment by wimdeblauwe** [comment]
https://github.com/wimdeblauwe/testcontainers-cypress/releases/tag/testcontainers-cypress-1.7.1 is now released with a fix to ignore such empty reports.
